Various quick script fixes
* Adds a `fail` function that was not already in place
* Renames `add_help` to `add_usage` to match the actual calls to
  the function
* Changes the `add_usage` implementation from `echo` to `cat`, as
  the previous implementation didn't work on my system's `bash`

diff --git a/bin/c3tk b/bin/c3tk
--- a/bin/c3tk
+++ b/bin/c3tk
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+fail() {
+  echo "FAIL: $*" >&2
+  exit 1
+}
+
 install_cmds() {
   for _cmd in "${@}"
   do
@@ -25,8 +30,8 @@ docker_run() {
   exec docker run --rm --platform="linux/amd64" -w '/w' -v ${PWD}:/w "${@}"
 }
 
-add_help() {
-  echo <<-HELP
+add_usage() {
+  cat <<-HELP
 c3tk add <name> image=<img> [tag=<tag>] [configs=.<a>,.<b>,...] [tty] [stream]
 
 Where:
